services:
   mongo:
     image: mongo:7
     container_name: franquicias-mongo
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db

   api:
     build: .
     container_name: franquicias-api
     ports:
       - "8080:8080"
     environment:
       SPRING_MONGODB_URI: mongodb://mongo:27017/franquicias
     depends_on:
       - mongo

volumes:
  mongo_data: